# Generated by Django 5.2.5 on 2025-08-16 11:53

import django.db.models.deletion
import signatures.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('filename', models.FileField(upload_to='documents/originals')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(default=signatures.models.make_token, max_length=64, unique=True)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='documents/signatures')),
                ('last_invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='signatures.document')),
                ('signee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.signee')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('document', 'position')},
            },
        ),
    ]
